// priority: 500
// Boss 遗物器官 — 有文本，无行为策略

RegistryOrgan('kubejs:storm_metal_plate')
    .addScore('chestcavity:health', 0.5)
    .addScore('chestcavity:nerves', 0.5)
    .addScore('chestcavity:breath_recovery', 0.5)
    .addScore('chestcavity:strength', 0.5)
    .addScore('chestcavity:filtration', 0.5)
    .addScore('chestcavity:detoxification', 0.5)
    .addScore('chestcavity:defense', 0.25)
    .addScore('chestcavity:nutrition', 0.25)
    .addScore('chestcavity:endurance', 0.5)
    .addScore('chestcavity:digestion', 0.25)
    .addScore('chestcavity:metabolism', 0.5)
    .addScore('chestcavity:breath_capacity', 0.5)
    .addScore('chestcavity:speed', 0.5)
    .addScore('chestcavity:burning_point', 2)
    .addScore('chestcavity:freezing_point', -2)
    .setCanSpawn(true)

RegistryOrgan('kubejs:parasitic_elf')
    .addScore('chestcavity:health', 1)
    .addScore('chestcavity:speed', -1)
    .addScore('chestcavity:hydrophobia', -1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:love_between_lava_and_ice')
    .addScore('chestcavity:health', 1.5)
    .addScore('chestcavity:fire_resistant', 0.5)
    .addScore('chestcavity:burning_point', 5)
    .addScore('chestcavity:freezing_point', -5)
    .setCanSpawn(true)

RegistryOrgan('kubejs:heart_of_blade')
    .addScore('chestcavity:health', -0.75)
    .setCanSpawn(true)

RegistryOrgan('kubejs:blade_of_heart')
    .addScore('chestcavity:defense', -1)
    .addScore('chestcavity:strength', 1.5)
    .setCanSpawn(true)

RegistryOrgan('kubejs:bone_soul')
    .addScore('chestcavity:defense', 0.5)
    .addScore('chestcavity:strength', 1)
    .addScore('chestcavity:endurance', -0.5)
    .setCanSpawn(true)

RegistryOrgan('kubejs:wither_and_fall')
    .addScore('chestcavity:health', -0.5)
    .addScore('chestcavity:photosynthesis', 0.5)
    .addScore('chestcavity:defense', -1.5)
    .addScore('chestcavity:nerves', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:melty_blood')
    .addScore('chestcavity:strength', 1.5)
    .addScore('chestcavity:speed', 1.0)
    .addScore('chestcavity:nerves', -0.25)
    .setCanSpawn(true)

RegistryOrgan('kubejs:mockery')
    .addScore('chestcavity:nerves', -0.25)
    .addScore('chestcavity:strength', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:sarcasm')
    .addScore('chestcavity:nerves', -0.25)
    .addScore('chestcavity:defense', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:cursed_soul')
    .addScore('chestcavity:strength', -1)
    .addScore('chestcavity:nerves', 1.25)
    .addScore('chestcavity:detoxification', -0.5)
    .setCanSpawn(true)

RegistryOrgan('kubejs:forbidden_fruit')
    .addScore('chestcavity:detoxification', 1.75)
    .addScore('chestcavity:health', 0.25)
    .setCanSpawn(true)

RegistryOrgan('kubejs:executioner_blade_pieces')
    .addScore('chestcavity:strength', 1.75)
    .addScore('chestcavity:health', -0.5)
    .setCanSpawn(true)

RegistryOrgan('kubejs:bloody_bone_arrow')
    .addScore('chestcavity:strength', 1.5)
    .addScore('chestcavity:health', -0.5)
    .addScore('chestcavity:speed', -1.0)
    .setCanSpawn(true)

RegistryOrgan('kubejs:heavy_hammer_muscle')
    .addScore('chestcavity:strength', 1.5)
    .addScore('chestcavity:swim_speed', -1)
    .addScore('chestcavity:fire_resistant', -1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:redstone_chipset')
    .addScore('chestcavity:nerves', 1.5)
    .addScore('chestcavity:fire_resistant', -1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:demon_eyeball')
    .addScore('chestcavity:luck', -1)
    .addScore('chestcavity:fire_resistant', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:sand_bone')
    .addScore('chestcavity:defense', 1)
    .addScore('chestcavity:fire_resistant', 1)
    .addScore('chestcavity:strength', 1.75)
    .setCanSpawn(true)

RegistryOrgan('kubejs:ancient_chip')
    .addScore('chestcavity:nerves', 1.25)
    .addScore('chestcavity:strength', 0.25)
    .setCanSpawn(true)

RegistryOrgan('kubejs:ring_for_home')
    .addScore('chestcavity:nerves', -0.25)
    .addScore('chestcavity:speed', -0.75)
    .setCanSpawn(true)

RegistryOrgan('kubejs:embers_liver')
    .addScore('chestcavity:detoxification', 1)
    .addScore('chestcavity:fire_resistant', 1)
    .addScore('chestcavity:hydroallergenic', 2)
    .addScore('chestcavity:strength', -1.5)
    .addScore('chestcavity:burning_point', 20)
    .addScore('chestcavity:freezing_point', 5)
    .setCanSpawn(true)

RegistryOrgan('kubejs:ender_guard_eyeball')
    .addScore('chestcavity:hydrophobia', 1)
    .addScore('chestcavity:luck', -1)
    .addScore('chestcavity:crystalsynthesis', 0.5)
    .setCanSpawn(true)

RegistryOrgan('kubejs:bad_ink')
    .addScore('chestcavity:strength', -1)
    .addScore('chestcavity:filtration', 0.5)
    .setCanSpawn(true)

RegistryOrgan('kubejs:freezing_intestine')
    .addScore('chestcavity:digestion', 1.25)
    .addScore('chestcavity:nutrition', 1.75)
    .addScore('chestcavity:burning_point', -5)
    .addScore('chestcavity:freezing_point', -10)
    .setCanSpawn(true)

RegistryOrgan('kubejs:blood_crystal')
    .addScore('chestcavity:crystalsynthesis', 1.5)
    .addScore('chestcavity:glowing', 1)
    .addScore('chestcavity:impact_resistant', 2)
    .setCanSpawn(true)

RegistryOrgan('kubejs:immortal_volcanic_rock')
    .addScore('chestcavity:hydroallergenic', 3)
    .addScore('chestcavity:swim_speed', -1)
    .addScore('chestcavity:burning_point', 10)
    .addScore('chestcavity:freezing_point', -10)
    .setCanSpawn(true)

RegistryOrgan('kubejs:fish_in_chest')
    .addScore('chestcavity:health', 0.25)
    .setCanSpawn(true)

RegistryOrgan('kubejs:vulcan_furnace')
    .addScore('chestcavity:strength', 1.75)
    .addScore('chestcavity:defense', -0.5)
    .setCanSpawn(true)

RegistryOrgan('kubejs:amethyst_magic_core')
    .addScore('chestcavity:health', 1.5)
    .addScore('chestcavity:nerves', 1.5)
    .setCanSpawn(true)

RegistryOrgan('kubejs:origin_knight_core')
    .addScore('chestcavity:health', 0.5)
    .addScore('chestcavity:defense', 2)
    .setCanSpawn(true)
