// priority: 500
RegistryOrgan('kubejs:relic_metal_plate')
    .addScore('chestcavity:health', 0.25)
    .addScore('chestcavity:nerves', 0.25)
    .addScore('chestcavity:breath_recovery', 0.25)
    .addScore('chestcavity:strength', 0.25)
    .addScore('chestcavity:filtration', 0.25)
    .addScore('chestcavity:detoxification', 0.25)
    .addScore('chestcavity:defense', 0.125)
    .addScore('chestcavity:nutrition', 0.125)
    .addScore('chestcavity:endurance', 0.25)
    .addScore('chestcavity:digestion', 0.125)
    .addScore('chestcavity:metabolism', 0.125)
    .addScore('chestcavity:breath_capacity', 0.125)
    .addScore('chestcavity:speed', 0.25)
    .addScore('chestcavity:burning_point', 1)
    .addScore('chestcavity:freezing_point', -1)
    .setCanSpawn(true)
