// priority: 500
// 七宗罪碎片 — active_only 行为

RegistryOrgan('kubejs:nether_star_shard')
    .addScore('chestcavity:fire_resistant', 0.5)
    .addScore('chestcavity:strength', 1)
    .addScore('chestcavity:defense', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:sloth_shard')
    .addScore('chestcavity:health', 3.5)
    .addScore('chestcavity:speed', -3)
    .addScore('chestcavity:defense', 3)
    .addScore('chestcavity:metabolism', -1.5)
    .setCanSpawn(true)

RegistryOrgan('kubejs:wrath_shard')
    .addScore('chestcavity:strength', 3)
    .addScore('chestcavity:nerves', -0.5)
    .addScore('chestcavity:defense', -2)
    .addScore('chestcavity:launching', 4.0)
    .addScore('chestcavity:burning_point', 5)
    .addScore('chestcavity:freezing_point', 10)
    .setCanSpawn(true)

RegistryOrgan('kubejs:envy_shard')
    .addScore('chestcavity:filtration', -1.5)
    .addScore('chestcavity:breath_recovery', 2)
    .addScore('chestcavity:endurance', -2.5)
    .addScore('chestcavity:speed', 2)
    .addScore('chestcavity:burning_point', -3)
    .addScore('chestcavity:freezing_point', -3)
    .setCanSpawn(true)

RegistryOrgan('kubejs:gluttony_shard')
    .addScore('chestcavity:health', -2.5)
    .addScore('chestcavity:digestion', 3)
    .addScore('chestcavity:nutrition', 2)
    .addScore('chestcavity:speed', -1.5)
    .addScore('chestcavity:burning_point', 10)
    .addScore('chestcavity:freezing_point', -10)
    .setCanSpawn(true)

RegistryOrgan('kubejs:lust_shard')
    .addScore('chestcavity:nerves', 2.5)
    .addScore('chestcavity:buff_purging', 2)
    .addScore('chestcavity:endurance', -2.5)
    .addScore('chestcavity:health', -1)
    .addScore('chestcavity:burning_point', 6)
    .addScore('chestcavity:freezing_point', 6)
    .setCanSpawn(true)

RegistryOrgan('kubejs:pride_shard')
    .addScore('chestcavity:crystalsynthesis', 1.5)
    .addScore('chestcavity:dragon_breath', 2)
    .addScore('chestcavity:defense', -3.5)
    .addScore('chestcavity:detoxification', 3.5)
    .addScore('chestcavity:burning_point', 6)
    .addScore('chestcavity:freezing_point', -6)
    .setCanSpawn(true)
