// priority: 500
StartupEvents.registry('item', event => {
    // 纯分数
    event.create('kubejs:warped_heart').maxStackSize(1).texture('kubejs:item/organs/alex/warped_heart').tag('kubejs:alex').tag('kubejs:heart')
    event.create('kubejs:warped_spine').maxStackSize(1).texture('kubejs:item/organs/alex/warped_spine').tag('kubejs:alex').tag('kubejs:spine')
    event.create('kubejs:feather').maxStackSize(1).texture('kubejs:item/organs/alex/feather').tag('kubejs:alex')
    event.create('kubejs:mollusk_muscle').maxStackSize(1).texture('kubejs:item/organs/alex/mollusk_muscle').tag('kubejs:alex').tag('kubejs:muscle')
    event.create('kubejs:giant_squid_whisker').maxStackSize(1).texture('kubejs:item/organs/alex/giant_squid_whisker').tag('kubejs:alex').tag('kubejs:muscle')
    event.create('kubejs:mimic_octopus_skin').maxStackSize(1).texture('kubejs:item/organs/alex/mimic_octopus_skin').tag('kubejs:alex')
    event.create('kubejs:fish_spine').maxStackSize(1).texture('kubejs:item/organs/alex/fish_spine').tag('kubejs:alex').tag('kubejs:spine')
    event.create('kubejs:fish_bone').maxStackSize(1).texture('kubejs:item/organs/alex/fish_bone').tag('kubejs:alex').tag('kubejs:rib')
    event.create('kubejs:fish_intestine').maxStackSize(1).texture('kubejs:item/organs/alex/fish_intestines').tag('kubejs:alex').tag('kubejs:intestine')
    // 有文本
    event.create('kubejs:tusk').maxStackSize(1).texture('kubejs:item/organs/alex/tusk').tag('kubejs:alex').tag('kubejs:damage_only')
    event.create('kubejs:soul_vulture_feather').maxStackSize(1).texture('kubejs:item/organs/alex/soul_vulture_feather').tag('kubejs:alex').tag('kubejs:damage_only')
    event.create('kubejs:fossil_gallbladder').maxStackSize(1).texture('kubejs:item/organs/alex/fossil_gallbladder').tag('kubejs:alex')
    event.create('kubejs:weird_paperman').maxStackSize(1).texture('kubejs:item/organs/alex/weird_paperman').tag('kubejs:alex').tag('kubejs:bear_only')
    event.create('kubejs:mosquito_repellent').maxStackSize(1).texture('kubejs:item/organs/alex/mosquito_repellent').tag('kubejs:alex').tag('kubejs:bear_only')
    // 有行为
    event.create('kubejs:sunbird_crystals').maxStackSize(1).texture('kubejs:item/organs/alex/sunbird_crystals').tag('kubejs:alex').tag('kubejs:damage_only').tag('kubejs:key_active')
    event.create('kubejs:enderiophage_heart').maxStackSize(1).texture('kubejs:item/organs/alex/enderiophage_heart').tag('kubejs:alex').tag('kubejs:heart').tag('kubejs:key_active')
    event.create('kubejs:whale_lung').maxStackSize(1).texture('kubejs:item/organs/alex/whale_lung').tag('kubejs:alex').tag('kubejs:lung')
    event.create('kubejs:mantis_shrimp_fist').maxStackSize(1).texture('kubejs:item/organs/alex/mantis_shrimp_fist').tag('kubejs:alex').tag('kubejs:muscle')
    event.create('kubejs:egg_of_straddler').maxStackSize(1).texture('kubejs:item/organs/alex/egg_of_straddler').tag('kubejs:alex')
    event.create('kubejs:potoo_beak').maxStackSize(1).texture('kubejs:item/organs/alex/potoo_beak').tag('kubejs:alex').tag('kubejs:key_active')
    event.create('kubejs:viviparous_crinoidea').maxStackSize(1).texture('kubejs:item/organs/alex/viviparous_crinoidea').tag('kubejs:alex').tag('kubejs:fantasy').tag('kubejs:key_active')
    event.create('kubejs:treasure_detector_feather')
        .maxStackSize(1)
        .texture('kubejs:item/organs/alex/treasure_detector_feather')
        .tag('kubejs:alex')
        .tag('kubejs:key_pressed')
        .tag('itemborders:gold')
        .tag('kubejs:key_active')
})
