// priority: 500
StartupEvents.registry('item', event => {
    // 纯分数
    event.create('kubejs:sculk_pieces').maxStackSize(1).texture('kubejs:item/organs/relics/sculk_pieces').tag('kubejs:relic').tag('kubejs:sculk')
    event.create('kubejs:warden_rib').maxStackSize(1).texture('kubejs:item/organs/relics/warden_rib').tag('kubejs:relic').tag('kubejs:rib')
    event.create('kubejs:warden_muscle').maxStackSize(1).texture('kubejs:item/organs/relics/warden_muscle').tag('kubejs:relic').tag('kubejs:muscle')
    event.create('kubejs:sculk_soul').maxStackSize(1).texture('kubejs:item/organs/relics/sculk_soul').tag('kubejs:relic').tag('kubejs:sculk')
    event.create('kubejs:flower_heart').maxStackSize(1).texture('kubejs:item/organs/relics/flower_heart').tag('kubejs:relic').tag('kubejs:heart')
    event.create('kubejs:void_worm_stomach').maxStackSize(1).texture('kubejs:item/organs/relics/void_worm_stomach').tag('kubejs:relic').tag('kubejs:stomach')
    event.create('kubejs:leviathan_spine').maxStackSize(1).texture('kubejs:item/organs/relics/leviathan_spine').tag('kubejs:relic').tag('kubejs:spine')
    event.create('kubejs:broken_prismarine_crown').maxStackSize(1).texture('kubejs:item/organs/relics/broken_prismarine_crown').tag('kubejs:relic')
    event.create('kubejs:frenzy_blast_furance').maxStackSize(1).texture('kubejs:item/organs/relics/frenzy_blast_furance').tag('kubejs:relic')
    // 有文本
    event.create('kubejs:storm_metal_plate').maxStackSize(1).texture('kubejs:item/organs/relics/storm_metal_plate').tag('kubejs:relic')
    event.create('kubejs:parasitic_elf').maxStackSize(1).texture('kubejs:item/organs/relics/parasitic_elf').tag('kubejs:relic').tag('kubejs:damage_only')
    event.create('kubejs:love_between_lava_and_ice').maxStackSize(1).texture('kubejs:item/organs/relics/love_between_lava_and_ice').tag('kubejs:relic').tag('kubejs:heart')
    event.create('kubejs:heart_of_blade').maxStackSize(1).texture('kubejs:item/organs/relics/heart_of_blade').tag('kubejs:relic').tag('kubejs:heart')
    event.create('kubejs:blade_of_heart').maxStackSize(1).texture('kubejs:item/organs/relics/blade_of_heart').tag('kubejs:relic').tag('kubejs:damage_only')
    event.create('kubejs:bone_soul').maxStackSize(1).texture('kubejs:item/organs/relics/bone_soul').tag('kubejs:relic').tag('kubejs:damage_only')
    event.create('kubejs:wither_and_fall').maxStackSize(1).texture('kubejs:item/organs/relics/wither_and_fall').tag('kubejs:relic').tag('kubejs:heart')
    event.create('kubejs:melty_blood').maxStackSize(1).texture('kubejs:item/organs/relics/melty_blood').tag('kubejs:relic').tag('kubejs:damage_only')
    event.create('kubejs:mockery').maxStackSize(1).texture('kubejs:item/organs/relics/mockery').tag('kubejs:relic').tag('kubejs:damage_only')
    event.create('kubejs:sarcasm').maxStackSize(1).texture('kubejs:item/organs/relics/sarcasm').tag('kubejs:relic')
    event.create('kubejs:cursed_soul').maxStackSize(1).texture('kubejs:item/organs/relics/cursed_soul').tag('kubejs:relic').tag('kubejs:warp')
    event.create('kubejs:forbidden_fruit').maxStackSize(1).texture('kubejs:item/organs/relics/forbidden_fruit').tag('kubejs:relic').tag('kubejs:liver')
    event.create('kubejs:executioner_blade_pieces').maxStackSize(1).texture('kubejs:item/organs/relics/executioner_blade_pieces').tag('kubejs:relic').tag('kubejs:muscle')
    event.create('kubejs:bloody_bone_arrow').maxStackSize(1).texture('kubejs:item/organs/relics/bloody_bone_arrow').tag('kubejs:relic').tag('kubejs:rib')
    event.create('kubejs:heavy_hammer_muscle').maxStackSize(1).texture('kubejs:item/organs/relics/heavy_hammer_muscle').tag('kubejs:relic').tag('kubejs:muscle')
    event.create('kubejs:redstone_chipset').maxStackSize(1).texture('kubejs:item/organs/relics/redstone_chipset').tag('kubejs:relic').tag('kubejs:machine')
    event.create('kubejs:demon_eyeball').maxStackSize(1).texture('kubejs:item/organs/relics/demon_eyeball').tag('kubejs:relic')
    event.create('kubejs:sand_bone').maxStackSize(1).texture('kubejs:item/organs/relics/sand_bone').tag('kubejs:relic')
    event.create('kubejs:ancient_chip').maxStackSize(1).texture('kubejs:item/organs/relics/ancient_chip').tag('kubejs:relic').tag('kubejs:machine')
    event.create('kubejs:ring_for_home').maxStackSize(1).texture('kubejs:item/organs/relics/ring_for_home').tag('kubejs:relic').tag('kubejs:magic')
    event.create('kubejs:embers_liver').maxStackSize(1).texture('kubejs:item/organs/relics/embers_liver').tag('kubejs:relic').tag('kubejs:liver')
    event.create('kubejs:ender_guard_eyeball').maxStackSize(1).texture('kubejs:item/organs/relics/ender_guard_eyeball').tag('kubejs:relic')
    event.create('kubejs:bad_ink').maxStackSize(1).texture('kubejs:item/organs/relics/bad_ink').tag('kubejs:relic').tag('kubejs:magic')
    event.create('kubejs:freezing_intestine').maxStackSize(1).texture('kubejs:item/organs/relics/freezing_intestine').tag('kubejs:relic').tag('kubejs:intestine')
    event.create('kubejs:blood_crystal').maxStackSize(1).texture('kubejs:item/organs/relics/blood_crystal').tag('kubejs:relic')
    event.create('kubejs:fish_in_chest').maxStackSize(1).texture('kubejs:item/organs/relics/fish_in_chest').tag('kubejs:relic')
    event.create('kubejs:vulcan_furnace').maxStackSize(1).texture('kubejs:item/organs/relics/vulcan_furnace').tag('kubejs:relic').tag('kubejs:machine')
    event.create('kubejs:amethyst_magic_core').maxStackSize(1).texture('kubejs:item/organs/relics/amethyst_magic_core').tag('kubejs:relic').tag('kubejs:heart')
    event.create('kubejs:origin_knight_core').maxStackSize(1).texture('kubejs:item/organs/relics/origin_knight_core').tag('kubejs:relic').tag('kubejs:heart')
})
