// priority: 500
StartupEvents.registry('item', event => {
    // 火龙
    event.create('kubejs:fire_dragon_bead').maxStackSize(1).texture('kubejs:item/organs/dragon/fire_dragon_bead').tag('kubejs:dragon').tag('kubejs:fire').tag('itemborders:diamond').tag('kubejs:key_pressed')
    event.create('kubejs:fire_dragon_lung').maxStackSize(1).texture('kubejs:item/organs/dragon/fire_dragon_lung').tag('kubejs:dragon').tag('kubejs:fire').tag('kubejs:lung').tag('itemborders:diamond')
    event.create('kubejs:fire_dragon_muscle').maxStackSize(1).texture('kubejs:item/organs/dragon/fire_dragon_muscle').tag('kubejs:dragon').tag('kubejs:fire').tag('kubejs:muscle').tag('itemborders:diamond')
    event.create('kubejs:fire_dragon_heart').maxStackSize(1).texture('kubejs:item/organs/dragon/fire_dragon_heart').tag('kubejs:dragon').tag('kubejs:fire').tag('kubejs:heart').tag('itemborders:diamond')
    event.create('kubejs:fire_dragon_intestine').maxStackSize(1).texture('kubejs:item/organs/dragon/fire_dragon_intestine').tag('kubejs:dragon').tag('kubejs:fire').tag('kubejs:intestine').tag('itemborders:diamond')
    event.create('kubejs:fire_dragon_rib').maxStackSize(1).texture('kubejs:item/organs/dragon/fire_dragon_rib').tag('kubejs:dragon').tag('kubejs:fire').tag('kubejs:rib').tag('itemborders:diamond')
    event.create('kubejs:fire_dragon_spine').maxStackSize(1).texture('kubejs:item/organs/dragon/fire_dragon_spine').tag('kubejs:dragon').tag('kubejs:fire').tag('kubejs:spine').tag('itemborders:diamond')
    event.create('kubejs:fire_dragon_spleen').maxStackSize(1).texture('kubejs:item/organs/dragon/fire_dragon_spleen').tag('kubejs:dragon').tag('kubejs:fire').tag('kubejs:spleen').tag('itemborders:diamond')
    event.create('kubejs:fire_dragon_stomach').maxStackSize(1).texture('kubejs:item/organs/dragon/fire_dragon_stomach').tag('kubejs:dragon').tag('kubejs:fire').tag('kubejs:stomach').tag('itemborders:diamond')
    event.create('kubejs:fire_dragon_kidney').maxStackSize(1).texture('kubejs:item/organs/dragon/fire_dragon_kidney').tag('kubejs:dragon').tag('kubejs:fire').tag('kubejs:kidney').tag('itemborders:diamond')
    event.create('kubejs:fire_dragon_liver').maxStackSize(1).texture('kubejs:item/organs/dragon/fire_dragon_liver').tag('kubejs:dragon').tag('kubejs:fire').tag('kubejs:liver').tag('itemborders:diamond')
    event.create('kubejs:fire_dragon_appendix').maxStackSize(1).texture('kubejs:item/organs/dragon/fire_dragon_appendix').tag('kubejs:dragon').tag('kubejs:fire').tag('kubejs:appendix').tag('itemborders:diamond')
    // 冰龙
    event.create('kubejs:ice_dragon_bead').maxStackSize(1).texture('kubejs:item/organs/dragon/ice_dragon_bead').tag('kubejs:dragon').tag('kubejs:ice').tag('itemborders:diamond')
    event.create('kubejs:ice_dragon_lung').maxStackSize(1).texture('kubejs:item/organs/dragon/ice_dragon_lung').tag('kubejs:dragon').tag('kubejs:ice').tag('kubejs:lung').tag('itemborders:diamond')
    event.create('kubejs:ice_dragon_muscle').maxStackSize(1).texture('kubejs:item/organs/dragon/ice_dragon_muscle').tag('kubejs:dragon').tag('kubejs:ice').tag('kubejs:muscle').tag('itemborders:diamond')
    event.create('kubejs:ice_dragon_heart').maxStackSize(1).texture('kubejs:item/organs/dragon/ice_dragon_heart').tag('kubejs:dragon').tag('kubejs:ice').tag('kubejs:heart').tag('itemborders:diamond')
    event.create('kubejs:ice_dragon_intestine').maxStackSize(1).texture('kubejs:item/organs/dragon/ice_dragon_intestine').tag('kubejs:dragon').tag('kubejs:ice').tag('kubejs:intestine').tag('itemborders:diamond')
    event.create('kubejs:ice_dragon_rib').maxStackSize(1).texture('kubejs:item/organs/dragon/ice_dragon_rib').tag('kubejs:dragon').tag('kubejs:ice').tag('kubejs:rib').tag('itemborders:diamond')
    event.create('kubejs:ice_dragon_spine').maxStackSize(1).texture('kubejs:item/organs/dragon/ice_dragon_spine').tag('kubejs:dragon').tag('kubejs:ice').tag('kubejs:spine').tag('itemborders:diamond')
    event.create('kubejs:ice_dragon_spleen').maxStackSize(1).texture('kubejs:item/organs/dragon/ice_dragon_spleen').tag('kubejs:dragon').tag('kubejs:ice').tag('kubejs:spleen').tag('itemborders:diamond')
    event.create('kubejs:ice_dragon_stomach').maxStackSize(1).texture('kubejs:item/organs/dragon/ice_dragon_stomach').tag('kubejs:dragon').tag('kubejs:ice').tag('kubejs:stomach').tag('itemborders:diamond')
    event.create('kubejs:ice_dragon_kidney').maxStackSize(1).texture('kubejs:item/organs/dragon/ice_dragon_kidney').tag('kubejs:dragon').tag('kubejs:ice').tag('kubejs:kidney').tag('itemborders:diamond')
    event.create('kubejs:ice_dragon_liver').maxStackSize(1).texture('kubejs:item/organs/dragon/ice_dragon_liver').tag('kubejs:dragon').tag('kubejs:ice').tag('kubejs:liver').tag('itemborders:diamond')
    event.create('kubejs:ice_dragon_appendix').maxStackSize(1).texture('kubejs:item/organs/dragon/ice_dragon_appendix').tag('kubejs:dragon').tag('kubejs:ice').tag('kubejs:appendix').tag('itemborders:diamond')
    // 电龙
    event.create('kubejs:lightning_dragon_bead').maxStackSize(1).texture('kubejs:item/organs/dragon/lightning_dragon_bead').tag('kubejs:dragon').tag('kubejs:lightning').tag('itemborders:diamond')
    event.create('kubejs:lightning_dragon_lung').maxStackSize(1).texture('kubejs:item/organs/dragon/lightning_dragon_lung').tag('kubejs:dragon').tag('kubejs:lightning').tag('kubejs:lung').tag('itemborders:diamond')
    event.create('kubejs:lightning_dragon_muscle').maxStackSize(1).texture('kubejs:item/organs/dragon/lightning_dragon_muscle').tag('kubejs:dragon').tag('kubejs:lightning').tag('kubejs:muscle').tag('itemborders:diamond')
    event.create('kubejs:lightning_dragon_heart').maxStackSize(1).texture('kubejs:item/organs/dragon/lightning_dragon_heart').tag('kubejs:dragon').tag('kubejs:lightning').tag('kubejs:heart').tag('itemborders:diamond')
    event.create('kubejs:lightning_dragon_intestine').maxStackSize(1).texture('kubejs:item/organs/dragon/lightning_dragon_intestine').tag('kubejs:dragon').tag('kubejs:lightning').tag('kubejs:intestine').tag('itemborders:diamond')
    event.create('kubejs:lightning_dragon_rib').maxStackSize(1).texture('kubejs:item/organs/dragon/lightning_dragon_rib').tag('kubejs:dragon').tag('kubejs:lightning').tag('kubejs:rib').tag('itemborders:diamond')
    event.create('kubejs:lightning_dragon_spine').maxStackSize(1).texture('kubejs:item/organs/dragon/lightning_dragon_spine').tag('kubejs:dragon').tag('kubejs:lightning').tag('kubejs:spine').tag('itemborders:diamond')
    event.create('kubejs:lightning_dragon_spleen').maxStackSize(1).texture('kubejs:item/organs/dragon/lightning_dragon_spleen').tag('kubejs:dragon').tag('kubejs:lightning').tag('kubejs:spleen').tag('itemborders:diamond')
    event.create('kubejs:lightning_dragon_stomach').maxStackSize(1).texture('kubejs:item/organs/dragon/lightning_dragon_stomach').tag('kubejs:dragon').tag('kubejs:lightning').tag('kubejs:stomach').tag('itemborders:diamond')
    event.create('kubejs:lightning_dragon_kidney').maxStackSize(1).texture('kubejs:item/organs/dragon/lightning_dragon_kidney').tag('kubejs:dragon').tag('kubejs:lightning').tag('kubejs:kidney').tag('itemborders:diamond')
    event.create('kubejs:lightning_dragon_liver').maxStackSize(1).texture('kubejs:item/organs/dragon/lightning_dragon_liver').tag('kubejs:dragon').tag('kubejs:lightning').tag('kubejs:liver').tag('itemborders:diamond')
    event.create('kubejs:lightning_dragon_appendix').maxStackSize(1).texture('kubejs:item/organs/dragon/lightning_dragon_appendix').tag('kubejs:dragon').tag('kubejs:lightning').tag('kubejs:appendix').tag('itemborders:diamond')
})