// priority: 500
StartupEvents.registry('item', event => {
    event.create('kubejs:lung_template').maxStackSize(1).texture('kubejs:item/organs/template/lung_template').tag('kubejs:evolution').tag('kubejs:lung')
    event.create('kubejs:muscle_template').maxStackSize(1).texture('kubejs:item/organs/template/muscle_template').tag('kubejs:evolution').tag('kubejs:muscle')
    event.create('kubejs:heart_template').maxStackSize(1).texture('kubejs:item/organs/template/heart_template').tag('kubejs:evolution').tag('kubejs:heart')
    event.create('kubejs:intestine_template').maxStackSize(1).texture('kubejs:item/organs/template/intestine_template').tag('kubejs:evolution').tag('kubejs:intestine')
    event.create('kubejs:rib_template').maxStackSize(1).texture('kubejs:item/organs/template/rib_template').tag('kubejs:evolution').tag('kubejs:rib')
    event.create('kubejs:spine_template').maxStackSize(1).texture('kubejs:item/organs/template/spine_template').tag('kubejs:evolution').tag('kubejs:spine')
    event.create('kubejs:spleen_template').maxStackSize(1).texture('kubejs:item/organs/template/spleen_template').tag('kubejs:evolution').tag('kubejs:spleen')
    event.create('kubejs:stomach_template').maxStackSize(1).texture('kubejs:item/organs/template/stomach_template').tag('kubejs:evolution').tag('kubejs:stomach')
    event.create('kubejs:kidney_template').maxStackSize(1).texture('kubejs:item/organs/template/kidney_template').tag('kubejs:evolution').tag('kubejs:kidney')
    event.create('kubejs:liver_template').maxStackSize(1).texture('kubejs:item/organs/template/liver_template').tag('kubejs:evolution').tag('kubejs:liver')
    event.create('kubejs:appendix_template').maxStackSize(1).texture('kubejs:item/organs/template/appendix_template').tag('kubejs:evolution').tag('kubejs:appendix')

    event.create('kubejs:lung_iron').maxStackSize(1).texture('kubejs:item/organs/common/lung').tag('kubejs:evolution').tag('kubejs:lung').tag('itemborders:iron')
    event.create('kubejs:muscle_iron').maxStackSize(1).texture('kubejs:item/organs/common/muscle').tag('kubejs:evolution').tag('kubejs:muscle').tag('itemborders:iron')
    event.create('kubejs:heart_iron').maxStackSize(1).texture('kubejs:item/organs/common/heart').tag('kubejs:evolution').tag('kubejs:heart').tag('itemborders:iron')
    event.create('kubejs:intestine_iron').maxStackSize(1).texture('kubejs:item/organs/common/intestine').tag('kubejs:evolution').tag('kubejs:intestine').tag('itemborders:iron')
    event.create('kubejs:rib_iron').maxStackSize(1).texture('kubejs:item/organs/common/rib').tag('kubejs:evolution').tag('kubejs:rib').tag('itemborders:iron')
    event.create('kubejs:spine_iron').maxStackSize(1).texture('kubejs:item/organs/common/spine').tag('kubejs:evolution').tag('kubejs:spine').tag('itemborders:iron')
    event.create('kubejs:spleen_iron').maxStackSize(1).texture('kubejs:item/organs/common/spleen').tag('kubejs:evolution').tag('kubejs:spleen').tag('itemborders:iron')
    event.create('kubejs:stomach_iron').maxStackSize(1).texture('kubejs:item/organs/common/stomach').tag('kubejs:evolution').tag('kubejs:stomach').tag('itemborders:iron')
    event.create('kubejs:kidney_iron').maxStackSize(1).texture('kubejs:item/organs/common/kidney').tag('kubejs:evolution').tag('kubejs:kidney').tag('itemborders:iron')
    event.create('kubejs:liver_iron').maxStackSize(1).texture('kubejs:item/organs/common/liver').tag('kubejs:evolution').tag('kubejs:liver').tag('itemborders:iron')
    event.create('kubejs:appendix_iron').maxStackSize(1).texture('kubejs:item/organs/common/appendix').tag('kubejs:evolution').tag('kubejs:appendix').tag('itemborders:iron')

    event.create('kubejs:lung_gold').maxStackSize(1).texture('kubejs:item/organs/common/lung').tag('kubejs:evolution').tag('kubejs:lung').tag('itemborders:gold')
    event.create('kubejs:muscle_gold').maxStackSize(1).texture('kubejs:item/organs/common/muscle').tag('kubejs:evolution').tag('kubejs:muscle').tag('itemborders:gold')
    event.create('kubejs:heart_gold').maxStackSize(1).texture('kubejs:item/organs/common/heart').tag('kubejs:evolution').tag('kubejs:heart').tag('itemborders:gold')
    event.create('kubejs:intestine_gold').maxStackSize(1).texture('kubejs:item/organs/common/intestine').tag('kubejs:evolution').tag('kubejs:intestine').tag('itemborders:gold')
    event.create('kubejs:rib_gold').maxStackSize(1).texture('kubejs:item/organs/common/rib').tag('kubejs:evolution').tag('kubejs:rib').tag('itemborders:gold')
    event.create('kubejs:spine_gold').maxStackSize(1).texture('kubejs:item/organs/common/spine').tag('kubejs:evolution').tag('kubejs:spine').tag('itemborders:gold')
    event.create('kubejs:spleen_gold').maxStackSize(1).texture('kubejs:item/organs/common/spleen').tag('kubejs:evolution').tag('kubejs:spleen').tag('itemborders:gold')
    event.create('kubejs:stomach_gold').maxStackSize(1).texture('kubejs:item/organs/common/stomach').tag('kubejs:evolution').tag('kubejs:stomach').tag('itemborders:gold')
    event.create('kubejs:kidney_gold').maxStackSize(1).texture('kubejs:item/organs/common/kidney').tag('kubejs:evolution').tag('kubejs:kidney').tag('itemborders:gold')
    event.create('kubejs:liver_gold').maxStackSize(1).texture('kubejs:item/organs/common/liver').tag('kubejs:evolution').tag('kubejs:liver').tag('itemborders:gold')
    event.create('kubejs:appendix_gold').maxStackSize(1).texture('kubejs:item/organs/common/appendix').tag('kubejs:evolution').tag('kubejs:appendix').tag('itemborders:gold')

    event.create('kubejs:lung_diamond').maxStackSize(1).texture('kubejs:item/organs/common/lung').tag('kubejs:diamond').tag('kubejs:lung').tag('itemborders:diamond')
    event.create('kubejs:muscle_diamond').maxStackSize(1).texture('kubejs:item/organs/common/muscle').tag('kubejs:diamond').tag('kubejs:muscle').tag('itemborders:diamond')
    event.create('kubejs:heart_diamond').maxStackSize(1).texture('kubejs:item/organs/common/heart').tag('kubejs:diamond').tag('kubejs:heart').tag('itemborders:diamond')
    event.create('kubejs:intestine_diamond').maxStackSize(1).texture('kubejs:item/organs/common/intestine').tag('kubejs:diamond').tag('kubejs:intestine').tag('itemborders:diamond')
    event.create('kubejs:rib_diamond').maxStackSize(1).texture('kubejs:item/organs/common/rib').tag('kubejs:diamond').tag('kubejs:rib').tag('itemborders:diamond')
    event.create('kubejs:spine_diamond').maxStackSize(1).texture('kubejs:item/organs/common/spine').tag('kubejs:diamond').tag('kubejs:spine').tag('itemborders:diamond')
    event.create('kubejs:spleen_diamond').maxStackSize(1).texture('kubejs:item/organs/common/spleen').tag('kubejs:diamond').tag('kubejs:spleen').tag('itemborders:diamond')
    event.create('kubejs:stomach_diamond').maxStackSize(1).texture('kubejs:item/organs/common/stomach').tag('kubejs:diamond').tag('kubejs:stomach').tag('itemborders:diamond')
    event.create('kubejs:kidney_diamond').maxStackSize(1).texture('kubejs:item/organs/common/kidney').tag('kubejs:diamond').tag('kubejs:kidney').tag('itemborders:diamond')
    event.create('kubejs:liver_diamond').maxStackSize(1).texture('kubejs:item/organs/common/liver').tag('kubejs:diamond').tag('kubejs:liver').tag('itemborders:diamond')
    event.create('kubejs:appendix_diamond').maxStackSize(1).texture('kubejs:item/organs/common/appendix').tag('kubejs:diamond').tag('kubejs:appendix').tag('itemborders:diamond')

    event.create('kubejs:hard_bone').maxStackSize(1).texture('minecraft:item/bone').tag('kubejs:rib').tag('itemborders:diamond')
    event.create('kubejs:soul_piece').maxStackSize(1).texture('kubejs:item/organs/others/soul_piece').tag('itemborders:gold')
})