// priority: 500
// 龙血器官 — 纯分数，无行为策略（dragon_blood_heart 在单独文件）

RegistryOrgan('kubejs:dragon_blood_lung')
    .addScore('chestcavity:strength', 0.75)
    .addScore('chestcavity:breath_recovery', 1.75)
    .addScore('chestcavity:breath_capacity', 1.75)
    .addScore('chestcavity:endurance', 1.75)
    .addScore('kubejs:dragon_blood', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:dragon_blood_muscle')
    .addScore('chestcavity:strength', 2.25)
    .addScore('chestcavity:speed', 1.75)
    .addScore('kubejs:dragon_blood', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:dragon_blood_intestine')
    .addScore('chestcavity:strength', 0.25)
    .addScore('chestcavity:nutrition', 1.75)
    .addScore('kubejs:dragon_blood', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:dragon_blood_rib')
    .addScore('chestcavity:strength', 0.25)
    .addScore('chestcavity:defense', 1.75)
    .addScore('kubejs:dragon_blood', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:dragon_blood_spine')
    .addScore('chestcavity:strength', 0.5)
    .addScore('chestcavity:defense', 0.75)
    .addScore('chestcavity:nerves', 1.75)
    .addScore('kubejs:dragon_blood', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:dragon_blood_spleen')
    .addScore('chestcavity:strength', 0.25)
    .addScore('chestcavity:metabolism', 1.75)
    .addScore('kubejs:dragon_blood', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:dragon_blood_stomach')
    .addScore('chestcavity:strength', 0.25)
    .addScore('chestcavity:digestion', 1.75)
    .addScore('kubejs:dragon_blood', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:dragon_blood_kidney')
    .addScore('chestcavity:strength', 0.25)
    .addScore('chestcavity:filtration', 1.75)
    .addScore('kubejs:dragon_blood', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:dragon_blood_liver')
    .addScore('chestcavity:strength', 0.25)
    .addScore('chestcavity:detoxification', 1.75)
    .addScore('kubejs:dragon_blood', 1)
    .setCanSpawn(true)

RegistryOrgan('kubejs:dragon_blood_appendix')
    .addScore('chestcavity:strength', 0.25)
    .addScore('chestcavity:luck', 1.75)
    .addScore('kubejs:dragon_blood', 1)
    .setCanSpawn(true)
