// priority: 900
// Alex Mobs 器官 tooltip

// 纯分数
RegistryOrganTooltip(new MultiStateTooltip('kubejs:warped_heart')
    .addDefault(Text.translatable('tooltips.kubejs.warped_heart.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:warped_spine')
    .addDefault(Text.translatable('tooltips.kubejs.warped_spine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:feather')
    .addDefault(Text.translatable('tooltips.kubejs.feather.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:mollusk_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.mollusk_muscle.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:giant_squid_whisker')
    .addDefault(Text.translatable('tooltips.kubejs.giant_squid_whisker.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:mimic_octopus_skin')
    .addDefault(Text.translatable('tooltips.kubejs.mimic_octopus_skin.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fish_spine')
    .addDefault(Text.translatable('tooltips.kubejs.fish_spine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fish_bone')
    .addDefault(Text.translatable('tooltips.kubejs.fish_bone.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fish_intestine')
    .addDefault(Text.translatable('tooltips.kubejs.fish_intestine.default.1').gray())
)

// 有文本
RegistryOrganTooltip(new MultiStateTooltip('kubejs:tusk')
    .addDefault(Text.translatable('tooltips.kubejs.tusk.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.tusk.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.tusk.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:soul_vulture_feather')
    .addDefault(Text.translatable('tooltips.kubejs.soul_vulture_feather.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.soul_vulture_feather.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fossil_gallbladder')
    .addDefault(Text.translatable('tooltips.kubejs.fossil_gallbladder.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.fossil_gallbladder.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:weird_paperman')
    .addDefault(Text.translatable('tooltips.kubejs.weird_paperman.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.weird_paperman.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:mosquito_repellent')
    .addDefault(Text.translatable('tooltips.kubejs.mosquito_repellent.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.mosquito_repellent.alt.1'))
)

// 有行为
RegistryOrganTooltip(new MultiStateTooltip('kubejs:sunbird_crystals')
    .addDefault(Text.translatable('tooltips.kubejs.sunbird_crystals.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.sunbird_crystals.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.sunbird_crystals.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:enderiophage_heart')
    .addDefault(Text.translatable('tooltips.kubejs.enderiophage_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.enderiophage_heart.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.enderiophage_heart.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:whale_lung')
    .addDefault(Text.translatable('tooltips.kubejs.whale_lung.default.1').gray())
    .addCtrl(Text.translatable('tooltips.kubejs.whale_lung.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:mantis_shrimp_fist')
    .addDefault(Text.translatable('tooltips.kubejs.mantis_shrimp_fist.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.mantis_shrimp_fist.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:egg_of_straddler')
    .addDefault(Text.translatable('tooltips.kubejs.egg_of_straddler.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.egg_of_straddler.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:potoo_beak')
    .addDefault(Text.translatable('tooltips.kubejs.potoo_beak.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.potoo_beak.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.potoo_beak.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:viviparous_crinoidea')
    .addDefault(Text.translatable('tooltips.kubejs.viviparous_crinoidea.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.viviparous_crinoidea.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.viviparous_crinoidea.alt.2'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:treasure_detector_feather')
    .addDefault(Text.translatable('tooltips.kubejs.treasure_detector_feather.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.treasure_detector_feather.alt.1', KeyActiveHover))
    .addAlt(Text.translatable('tooltips.kubejs.treasure_detector_feather.alt.2'))
)
