// priority: 900
// Boss 遗物器官 tooltip

// 纯分数
RegistryOrganTooltip(new MultiStateTooltip('kubejs:sculk_pieces')
    .addDefault(Text.translatable('tooltips.kubejs.sculk_pieces.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:warden_rib')
    .addDefault(Text.translatable('tooltips.kubejs.warden_rib.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:warden_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.warden_muscle.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:sculk_soul')
    .addDefault(Text.translatable('tooltips.kubejs.sculk_soul.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:flower_heart')
    .addDefault(Text.translatable('tooltips.kubejs.flower_heart.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:void_worm_stomach')
    .addDefault(Text.translatable('tooltips.kubejs.void_worm_stomach.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:leviathan_spine')
    .addDefault(Text.translatable('tooltips.kubejs.leviathan_spine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:broken_prismarine_crown')
    .addDefault(Text.translatable('tooltips.kubejs.broken_prismarine_crown.default.1').gray())
    .addCtrl(Text.translatable('tooltips.kubejs.broken_prismarine_crown.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:frenzy_blast_furance')
    .addDefault(Text.translatable('tooltips.kubejs.frenzy_blast_furance.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.frenzy_blast_furance.alt.1'))
)

// 有文本
RegistryOrganTooltip(new MultiStateTooltip('kubejs:storm_metal_plate')
    .addDefault(Text.translatable('tooltips.kubejs.storm_metal_plate.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:parasitic_elf')
    .addDefault(Text.translatable('tooltips.kubejs.parasitic_elf.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.parasitic_elf.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:love_between_lava_and_ice')
    .addDefault(Text.translatable('tooltips.kubejs.love_between_lava_and_ice.default.1').gray())
    .addCtrl(Text.translatable('tooltips.kubejs.love_between_lava_and_ice.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.love_between_lava_and_ice.ctrl.2'))
    .addCtrl(Text.translatable('tooltips.kubejs.love_between_lava_and_ice.ctrl.3'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:heart_of_blade')
    .addDefault(Text.translatable('tooltips.kubejs.heart_of_blade.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.heart_of_blade.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:blade_of_heart')
    .addDefault(Text.translatable('tooltips.kubejs.blade_of_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.blade_of_heart.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:bone_soul')
    .addDefault(Text.translatable('tooltips.kubejs.bone_soul.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.bone_soul.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.bone_soul.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:wither_and_fall')
    .addDefault(Text.translatable('tooltips.kubejs.wither_and_fall.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.wither_and_fall.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.wither_and_fall.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.wither_and_fall.alt.3'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:melty_blood')
    .addDefault(Text.translatable('tooltips.kubejs.melty_blood.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.melty_blood.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.melty_blood.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:mockery')
    .addDefault(Text.translatable('tooltips.kubejs.mockery.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.mockery.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.mockery.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:sarcasm')
    .addDefault(Text.translatable('tooltips.kubejs.sarcasm.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.sarcasm.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.sarcasm.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:cursed_soul')
    .addDefault(Text.translatable('tooltips.kubejs.cursed_soul.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.cursed_soul.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.cursed_soul.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:forbidden_fruit')
    .addDefault(Text.translatable('tooltips.kubejs.forbidden_fruit.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.forbidden_fruit.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:executioner_blade_pieces')
    .addDefault(Text.translatable('tooltips.kubejs.executioner_blade_pieces.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.executioner_blade_pieces.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.executioner_blade_pieces.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:bloody_bone_arrow')
    .addDefault(Text.translatable('tooltips.kubejs.bloody_bone_arrow.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.bloody_bone_arrow.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.bloody_bone_arrow.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:heavy_hammer_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.heavy_hammer_muscle.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.heavy_hammer_muscle.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:redstone_chipset')
    .addDefault(Text.translatable('tooltips.kubejs.redstone_chipset.default.1').gray())
    .addCtrl(Text.translatable('tooltips.kubejs.redstone_chipset.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.redstone_chipset.ctrl.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:demon_eyeball')
    .addDefault(Text.translatable('tooltips.kubejs.demon_eyeball.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.demon_eyeball.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.demon_eyeball.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:sand_bone')
    .addDefault(Text.translatable('tooltips.kubejs.sand_bone.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.sand_bone.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ancient_chip')
    .addDefault(Text.translatable('tooltips.kubejs.ancient_chip.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ancient_chip.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ring_for_home')
    .addDefault(Text.translatable('tooltips.kubejs.ring_for_home.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ring_for_home.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:embers_liver')
    .addDefault(Text.translatable('tooltips.kubejs.embers_liver.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.embers_liver.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.embers_liver.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ender_guard_eyeball')
    .addDefault(Text.translatable('tooltips.kubejs.ender_guard_eyeball.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ender_guard_eyeball.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:bad_ink')
    .addDefault(Text.translatable('tooltips.kubejs.bad_ink.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:freezing_intestine')
    .addDefault(Text.translatable('tooltips.kubejs.freezing_intestine.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.freezing_intestine.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:blood_crystal')
    .addDefault(Text.translatable('tooltips.kubejs.blood_crystal.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.blood_crystal.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.blood_crystal.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:immortal_volcanic_rock')
    .addDefault(Text.translatable('tooltips.kubejs.immortal_volcanic_rock.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.immortal_volcanic_rock.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fish_in_chest')
    .addDefault(Text.translatable('tooltips.kubejs.fish_in_chest.default.1').gray())
    .addCtrl(Text.translatable('tooltips.kubejs.fish_in_chest.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.fish_in_chest.ctrl.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:vulcan_furnace')
    .addDefault(Text.translatable('tooltips.kubejs.vulcan_furnace.default.1').gray())
    .addCtrl(Text.translatable('tooltips.kubejs.vulcan_furnace.ctrl.1'))
    .addAlt(Text.translatable('tooltips.kubejs.vulcan_furnace.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.vulcan_furnace.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:amethyst_magic_core')
    .addDefault(Text.translatable('tooltips.kubejs.amethyst_magic_core.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.amethyst_magic_core.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.amethyst_magic_core.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:origin_knight_core')
    .addDefault(Text.translatable('tooltips.kubejs.origin_knight_core.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.origin_knight_core.alt.1'))
)