// priority: 900
// 火龙器官 tooltip
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fire_dragon_bead')
    .addDefault(Text.translatable('tooltips.kubejs.fire_dragon_bead.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.fire_dragon_bead.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.fire_dragon_bead.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.fire_dragon_bead.alt.3'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fire_dragon_lung')
    .addDefault(Text.translatable('tooltips.kubejs.fire_dragon_lung.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fire_dragon_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.fire_dragon_muscle.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fire_dragon_heart')
    .addDefault(Text.translatable('tooltips.kubejs.fire_dragon_heart.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fire_dragon_intestine')
    .addDefault(Text.translatable('tooltips.kubejs.fire_dragon_intestine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fire_dragon_rib')
    .addDefault(Text.translatable('tooltips.kubejs.fire_dragon_rib.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fire_dragon_spine')
    .addDefault(Text.translatable('tooltips.kubejs.fire_dragon_spine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fire_dragon_spleen')
    .addDefault(Text.translatable('tooltips.kubejs.fire_dragon_spleen.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fire_dragon_stomach')
    .addDefault(Text.translatable('tooltips.kubejs.fire_dragon_stomach.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fire_dragon_kidney')
    .addDefault(Text.translatable('tooltips.kubejs.fire_dragon_kidney.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fire_dragon_liver')
    .addDefault(Text.translatable('tooltips.kubejs.fire_dragon_liver.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fire_dragon_appendix')
    .addDefault(Text.translatable('tooltips.kubejs.fire_dragon_appendix.default.1').gray())
)

// 冰龙器官 tooltip
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_dragon_bead')
    .addDefault(Text.translatable('tooltips.kubejs.ice_dragon_bead.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ice_dragon_bead.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.ice_dragon_bead.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.ice_dragon_bead.alt.3'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_dragon_lung')
    .addDefault(Text.translatable('tooltips.kubejs.ice_dragon_lung.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_dragon_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.ice_dragon_muscle.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_dragon_heart')
    .addDefault(Text.translatable('tooltips.kubejs.ice_dragon_heart.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_dragon_intestine')
    .addDefault(Text.translatable('tooltips.kubejs.ice_dragon_intestine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_dragon_rib')
    .addDefault(Text.translatable('tooltips.kubejs.ice_dragon_rib.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_dragon_spine')
    .addDefault(Text.translatable('tooltips.kubejs.ice_dragon_spine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_dragon_spleen')
    .addDefault(Text.translatable('tooltips.kubejs.ice_dragon_spleen.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_dragon_stomach')
    .addDefault(Text.translatable('tooltips.kubejs.ice_dragon_stomach.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_dragon_kidney')
    .addDefault(Text.translatable('tooltips.kubejs.ice_dragon_kidney.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_dragon_liver')
    .addDefault(Text.translatable('tooltips.kubejs.ice_dragon_liver.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_dragon_appendix')
    .addDefault(Text.translatable('tooltips.kubejs.ice_dragon_appendix.default.1').gray())
)

// 电龙器官 tooltip
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lightning_dragon_bead')
    .addDefault(Text.translatable('tooltips.kubejs.lightning_dragon_bead.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.lightning_dragon_bead.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.lightning_dragon_bead.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.lightning_dragon_bead.alt.3'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lightning_dragon_lung')
    .addDefault(Text.translatable('tooltips.kubejs.lightning_dragon_lung.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lightning_dragon_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.lightning_dragon_muscle.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lightning_dragon_heart')
    .addDefault(Text.translatable('tooltips.kubejs.lightning_dragon_heart.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lightning_dragon_intestine')
    .addDefault(Text.translatable('tooltips.kubejs.lightning_dragon_intestine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lightning_dragon_rib')
    .addDefault(Text.translatable('tooltips.kubejs.lightning_dragon_rib.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lightning_dragon_spine')
    .addDefault(Text.translatable('tooltips.kubejs.lightning_dragon_spine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lightning_dragon_spleen')
    .addDefault(Text.translatable('tooltips.kubejs.lightning_dragon_spleen.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lightning_dragon_stomach')
    .addDefault(Text.translatable('tooltips.kubejs.lightning_dragon_stomach.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lightning_dragon_kidney')
    .addDefault(Text.translatable('tooltips.kubejs.lightning_dragon_kidney.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lightning_dragon_liver')
    .addDefault(Text.translatable('tooltips.kubejs.lightning_dragon_liver.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lightning_dragon_appendix')
    .addDefault(Text.translatable('tooltips.kubejs.lightning_dragon_appendix.default.1').gray())
)
