// priority: 900
// 模板器官 tooltip
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lung_template')
    .addDefault(Text.translatable('tooltips.kubejs.lung_template.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:muscle_template')
    .addDefault(Text.translatable('tooltips.kubejs.muscle_template.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:heart_template')
    .addDefault(Text.translatable('tooltips.kubejs.heart_template.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:intestine_template')
    .addDefault(Text.translatable('tooltips.kubejs.intestine_template.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:rib_template')
    .addDefault(Text.translatable('tooltips.kubejs.rib_template.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:spine_template')
    .addDefault(Text.translatable('tooltips.kubejs.spine_template.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:spleen_template')
    .addDefault(Text.translatable('tooltips.kubejs.spleen_template.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:stomach_template')
    .addDefault(Text.translatable('tooltips.kubejs.stomach_template.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:kidney_template')
    .addDefault(Text.translatable('tooltips.kubejs.kidney_template.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:liver_template')
    .addDefault(Text.translatable('tooltips.kubejs.liver_template.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:appendix_template')
    .addDefault(Text.translatable('tooltips.kubejs.appendix_template.default.1').gray())
)

// 硬骨 tooltip
RegistryOrganTooltip(new MultiStateTooltip('kubejs:hard_bone')
    .addDefault(Text.translatable('tooltips.kubejs.hard_bone.default.1').gray())
)
