// priority: 900
// 幻想种器官 tooltip
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fantasy_lung')
    .addDefault(Text.translatable('tooltips.kubejs.fantasy_lung.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fantasy_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.fantasy_muscle.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fantasy_heart')
    .addDefault(Text.translatable('tooltips.kubejs.fantasy_heart.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fantasy_intestine')
    .addDefault(Text.translatable('tooltips.kubejs.fantasy_intestine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fantasy_rib')
    .addDefault(Text.translatable('tooltips.kubejs.fantasy_rib.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fantasy_spine')
    .addDefault(Text.translatable('tooltips.kubejs.fantasy_spine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fantasy_spleen')
    .addDefault(Text.translatable('tooltips.kubejs.fantasy_spleen.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fantasy_stomach')
    .addDefault(Text.translatable('tooltips.kubejs.fantasy_stomach.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fantasy_kidney')
    .addDefault(Text.translatable('tooltips.kubejs.fantasy_kidney.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fantasy_liver')
    .addDefault(Text.translatable('tooltips.kubejs.fantasy_liver.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fantasy_appendix')
    .addDefault(Text.translatable('tooltips.kubejs.fantasy_appendix.default.1').gray())
)
