// priority: 900
// 巨型器官 tooltip
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_lung')
    .addDefault(Text.translatable('tooltips.kubejs.huge_lung.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.huge_lung.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.huge_muscle.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.huge_muscle.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_heart')
    .addDefault(Text.translatable('tooltips.kubejs.huge_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.huge_heart.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_intestine')
    .addDefault(Text.translatable('tooltips.kubejs.huge_intestine.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.huge_intestine.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_rib')
    .addDefault(Text.translatable('tooltips.kubejs.huge_rib.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.huge_rib.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_spine')
    .addDefault(Text.translatable('tooltips.kubejs.huge_spine.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.huge_spine.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_spleen')
    .addDefault(Text.translatable('tooltips.kubejs.huge_spleen.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.huge_spleen.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_stomach')
    .addDefault(Text.translatable('tooltips.kubejs.huge_stomach.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.huge_stomach.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_kidney')
    .addDefault(Text.translatable('tooltips.kubejs.huge_kidney.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.huge_kidney.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_liver')
    .addDefault(Text.translatable('tooltips.kubejs.huge_liver.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.huge_liver.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_appendix')
    .addDefault(Text.translatable('tooltips.kubejs.huge_appendix.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.huge_appendix.alt.1'))
)
