// priority: 900
// 巨型器官 tooltip
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_lung')
    .addCtrl(Text.translatable('tooltips.kubejs.huge_lung.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_muscle')
    .addCtrl(Text.translatable('tooltips.kubejs.huge_muscle.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_heart')
    .addCtrl(Text.translatable('tooltips.kubejs.huge_heart.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_intestine')
    .addCtrl(Text.translatable('tooltips.kubejs.huge_intestine.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_rib')
    .addCtrl(Text.translatable('tooltips.kubejs.huge_rib.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_spine')
    .addCtrl(Text.translatable('tooltips.kubejs.huge_spine.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_spleen')
    .addCtrl(Text.translatable('tooltips.kubejs.huge_spleen.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_stomach')
    .addCtrl(Text.translatable('tooltips.kubejs.huge_stomach.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_kidney')
    .addCtrl(Text.translatable('tooltips.kubejs.huge_kidney.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_liver')
    .addCtrl(Text.translatable('tooltips.kubejs.huge_liver.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:huge_appendix')
    .addCtrl(Text.translatable('tooltips.kubejs.huge_appendix.ctrl.1'))
)