// priority: 900
RegistryOrganTooltip(new MultiStateTooltip('kubejs:prismarine_crown')
    .addDefault(Text.translatable('tooltips.kubejs.prismarine_crown.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.prismarine_crown.alt.1', Text.gold('0'), Text.gold('0')))
    .addAlt(Text.translatable('tooltips.kubejs.prismarine_crown.alt.2', Text.gold('3'), Text.gold('3')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:infinity_beats')
    .addAlt(Text.translatable('tooltips.kubejs.infinity_beats.alt.1', Text.yellow('4')).gray())
    .addAlt(Text.translatable('tooltips.kubejs.infinity_beats.alt.2').gray())
    .addAlt(Text.translatable('tooltips.kubejs.infinity_beats.alt.3').gray())
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:doppelganger')
    .addDefault(Text.translatable('tooltips.kubejs.doppelganger.default.1').gray())
    .addDefault(Text.translatable('tooltips.kubejs.doppelganger.default.2').gray())
    .addAlt(Text.translatable('tooltips.kubejs.doppelganger.alt.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.doppelganger.alt.2', Text.gold('25%'), Text.gold('10%')).gray())
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:pandora_inactive')
    .addDefault(Text.translatable('tooltips.kubejs.pandora_inactive.default.1').gray())
    .addDefault(Text.translatable('tooltips.kubejs.pandora_inactive.default.2').darkPurple())
    .addAlt(Text.translatable('tooltips.kubejs.pandora_inactive.alt.1', Text.gold('3'), Text.gold('5')).gray())
    .addAlt(Text.translatable('tooltips.kubejs.pandora_inactive.alt.2', Text.gold('5'), Text.gold('7')).gray())
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:infinity_force')
    .addDefault(Text.translatable('tooltips.kubejs.infinity_force.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.infinity_force.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.infinity_force.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.infinity_force.alt.3'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:long_lasting_pill')
    .addDefault(Text.translatable('tooltips.kubejs.long_lasting_pill.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:d8')
    .addDefault(Text.translatable('tooltips.kubejs.d8.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:genesis')
    .addDefault(Text.translatable('tooltips.kubejs.genesis.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:go_camping')
    .addDefault(Text.translatable('tooltips.kubejs.go_camping.default.1').gray())
)
