// priority: 900
RegistryOrganTooltip(new MultiStateTooltip('kubejs:furnace_core')
    .addDefault(Text.translatable('tooltips.kubejs.furnace_core.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.furnace_core.alt.1', Text.gold('100')))
    .addAlt(Text.translatable('tooltips.kubejs.furnace_core.alt.2', Text.gold('2'), Text.gold('5')))
    .addAlt(Text.translatable('tooltips.kubejs.furnace_core.alt.3'))
    .addCtrl(RevolutionFlameType)
    .addCtrl(Text.translatable('tooltips.kubejs.furnace_core.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.furnace_core.ctrl.2'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:burning_heart')
    .addDefault(Text.translatable('tooltips.kubejs.burning_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.burning_heart.alt.1', Text.gold('5')))
    .addAlt(Text.translatable('tooltips.kubejs.burning_heart.alt.2', Text.gold('100%')))
    .addAlt(Text.translatable('tooltips.kubejs.burning_heart.alt.3'))
    .addCtrl(RevolutionFlameType)
    .addCtrl(Text.translatable('tooltips.kubejs.burning_heart.ctrl.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:energy_bottle_red')
    .addDefault(Text.translatable('tooltips.kubejs.energy_bottle_red.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.energy_bottle_red.alt.1', Text.gold('100')))
    .addAlt(Text.translatable('tooltips.kubejs.energy_bottle_red.alt.2', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.energy_bottle_red.ctrl.1', Text.gold('300%')))
    .addCtrl(RevolutionFlameType)
    .addCtrl(Text.translatable('tooltips.kubejs.energy_bottle_red.ctrl.2', Text.gold('200%')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:revolution_cable')
    .addDefault(Text.translatable('tooltips.kubejs.revolution_cable.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_cable.alt.1', Text.gold('1')))
    .addAlt(Text.translatable('tooltips.kubejs.revolution_cable.alt.2', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.revolution_cable.ctrl.1', Text.gold('300%')))
)


RegistryOrganTooltip(new MultiStateTooltip('kubejs:revolution_relay')
    .addDefault(Text.translatable('tooltips.kubejs.revolution_relay.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_relay.alt.1', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.revolution_relay.ctrl.1', Text.gold('300%')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:revolution_delay')
    .addDefault(Text.translatable('tooltips.kubejs.revolution_delay.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_delay.alt.1', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.revolution_delay.ctrl.1', Text.gold('300%')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:revolution_bell')
    .addDefault(Text.translatable('tooltips.kubejs.revolution_bell.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_bell.alt.1', KeyActiveHover))
    .addAlt(Text.translatable('tooltips.kubejs.revolution_bell.alt.2'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:blaze_pressurizer')
    .addDefault(Text.translatable('tooltips.kubejs.blaze_pressurizer.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.blaze_pressurizer.alt.1', KeyActiveHover, Text.gold('3')))
    .addAlt(Text.translatable('tooltips.kubejs.blaze_pressurizer.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.blaze_pressurizer.alt.3'))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.blaze_pressurizer.ctrl.1', Text.gold('300%')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:telescopic_arm')
    .addDefault(Text.translatable('tooltips.kubejs.telescopic_arm.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.telescopic_arm.alt.1', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.telescopic_arm.ctrl.1', Text.gold('4')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:telescopic_attack_arm')
    .addDefault(Text.translatable('tooltips.kubejs.telescopic_attack_arm.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.telescopic_attack_arm.alt.1', Text.gold('0.5')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.telescopic_attack_arm.ctrl.1', Text.gold('2')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:lava_life_cycle_system')
    .addDefault(Text.translatable('tooltips.kubejs.lava_life_cycle_system.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.lava_life_cycle_system.alt.1', DirectlyNearbyOrganHover))
    .addAlt(Text.translatable('tooltips.kubejs.lava_life_cycle_system.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.lava_life_cycle_system.alt.3'))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.lava_life_cycle_system.ctrl.1', Text.gold('300')))
)


RegistryOrganTooltip(new MultiStateTooltip('kubejs:prowler_rotating_shaft')
    .addDefault(Text.translatable('tooltips.kubejs.prowler_rotating_shaft.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.prowler_rotating_shaft.alt.1', Text.gold('1'), Text.gold('16')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:watcher_probe')
    .addDefault(Text.translatable('tooltips.kubejs.watcher_probe.default.1').gray())
)


RegistryOrganTooltip(new MultiStateTooltip('kubejs:fiery_core')
    .addDefault(Text.translatable('tooltips.kubejs.fiery_core.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.fiery_core.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.fiery_core.alt.2'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:thermometer')
    .addDefault(Text.translatable('tooltips.kubejs.thermometer.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.thermometer.alt.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:small_acid_tank')
    .addDefault(Text.translatable('tooltips.kubejs.small_acid_tank.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.small_acid_tank.alt.1', Text.gold('1')))
    .addAlt(Text.translatable('tooltips.kubejs.small_acid_tank.alt.2', Text.gold('1'), Player17TypeHover, Player21TypeHover))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:iron_repair_device')
    .addDefault(Text.translatable('tooltips.kubejs.iron_repair_device.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.iron_repair_device.alt.1', Text.gold('10%')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:cyborgization_device')
    .addDefault(Text.translatable('tooltips.kubejs.cyborgization_device.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.cyborgization_device.alt.1', RevolutionMachineTypeHover))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:programmable_automatic_core')
    .addDefault(Text.translatable('tooltips.kubejs.programmable_automatic_core.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.programmable_automatic_core.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.programmable_automatic_core.alt.2', Text.gold('1')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:revolution_steam_engine')
    .addDefault(Text.translatable('tooltips.kubejs.revolution_steam_engine.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_steam_engine.alt.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_steam_engine.alt.2').gray())
)

// 缺失的机械器官 tooltip
RegistryOrganTooltip(new MultiStateTooltip('kubejs:revolution_gear')
    .addDefault(Text.translatable('tooltips.kubejs.revolution_gear.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_gear.alt.1', Text.gold('1')))
    .addAlt(Text.translatable('tooltips.kubejs.revolution_gear.alt.2', Text.gold('2')))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:compressed_oxygen_implant')
    .addDefault(Text.translatable('tooltips.kubejs.compressed_oxygen_implant.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lowlight_vision')
    .addDefault(Text.translatable('tooltips.kubejs.lowlight_vision.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.lowlight_vision.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:jet_propeller')
    .addDefault(Text.translatable('tooltips.kubejs.jet_propeller.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.jet_propeller.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.jet_propeller.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:aegis')
    .addDefault(Text.translatable('tooltips.kubejs.aegis.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.aegis.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.aegis.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:mace')
    .addDefault(Text.translatable('tooltips.kubejs.mace.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.mace.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.mace.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:platelet_dispatcher')
    .addDefault(Text.translatable('tooltips.kubejs.platelet_dispatcher.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.platelet_dispatcher.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.platelet_dispatcher.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:machine_clockwork')
    .addDefault(Text.translatable('tooltips.kubejs.machine_clockwork.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.machine_clockwork.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.machine_clockwork.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:tamagotchi')
    .addDefault(Text.translatable('tooltips.kubejs.tamagotchi.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.tamagotchi.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.tamagotchi.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.tamagotchi.alt.3'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:energy_bottle_max')
    .addDefault(Text.translatable('tooltips.kubejs.energy_bottle_max.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.energy_bottle_max.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.energy_bottle_max.alt.2'))
)