// priority: 900
// 缺失的魔法使/糖果/禁忌/传说/食物器官 tooltip

// 糖果
RegistryOrganTooltip(new MultiStateTooltip('kubejs:candy_heart')
    .addDefault(Text.translatable('tooltips.kubejs.candy_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.candy_heart.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.candy_heart.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:candy_pancreas')
    .addDefault(Text.translatable('tooltips.kubejs.candy_pancreas.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.candy_pancreas.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.candy_pancreas.alt.2'))
)

// 魔法使
RegistryOrganTooltip(new MultiStateTooltip('kubejs:plastic_heart')
    .addDefault(Text.translatable('tooltips.kubejs.plastic_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.plastic_heart.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:magic_hippocampus')
    .addDefault(Text.translatable('tooltips.kubejs.magic_hippocampus.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.magic_hippocampus.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.magic_hippocampus.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:magic_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.magic_muscle.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:magic_spine')
    .addDefault(Text.translatable('tooltips.kubejs.magic_spine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:magic_vision')
    .addDefault(Text.translatable('tooltips.kubejs.magic_vision.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.magic_vision.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.magic_vision.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:color_palette')
    .addDefault(Text.translatable('tooltips.kubejs.color_palette.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.color_palette.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:red_ink')
    .addDefault(Text.translatable('tooltips.kubejs.red_ink.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:blood_moon_wand')
    .addDefault(Text.translatable('tooltips.kubejs.blood_moon_wand.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:is_rabbit')
    .addDefault(Text.translatable('tooltips.kubejs.is_rabbit.default.1').gray())
)

// 禁忌
RegistryOrganTooltip(new MultiStateTooltip('kubejs:the_third_eye')
    .addDefault(Text.translatable('tooltips.kubejs.the_third_eye.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.the_third_eye.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:fish_in_warp')
    .addDefault(Text.translatable('tooltips.kubejs.fish_in_warp.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.fish_in_warp.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:disenchantment_paper')
    .addDefault(Text.translatable('tooltips.kubejs.disenchantment_paper.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.disenchantment_paper.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.disenchantment_paper.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:warp_bubble')
    .addDefault(Text.translatable('tooltips.kubejs.warp_bubble.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.warp_bubble.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.warp_bubble.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:pandora_active')
    .addDefault(Text.translatable('tooltips.kubejs.pandora_active.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.pandora_active.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.pandora_active.alt.2'))
)

// 传说
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lost_paradise')
    .addDefault(Text.translatable('tooltips.kubejs.lost_paradise.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.lost_paradise.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.lost_paradise.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.lost_paradise.alt.3'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:paradise_regained')
    .addDefault(Text.translatable('tooltips.kubejs.paradise_regained.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.paradise_regained.alt.1'))
)

// 食物
RegistryOrganTooltip(new MultiStateTooltip('kubejs:hamimelon_organ')
    .addDefault(Text.translatable('tooltips.kubejs.hamimelon_organ.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:watermelon_organ')
    .addDefault(Text.translatable('tooltips.kubejs.watermelon_organ.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lucky_cookie_organ')
    .addDefault(Text.translatable('tooltips.kubejs.lucky_cookie_organ.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:golden_lucky_cookie_organ')
    .addDefault(Text.translatable('tooltips.kubejs.golden_lucky_cookie_organ.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.golden_lucky_cookie_organ.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:cream_cookie_heart')
    .addDefault(Text.translatable('tooltips.kubejs.cream_cookie_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.cream_cookie_heart.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.cream_cookie_heart.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:mini_slime')
    .addDefault(Text.translatable('tooltips.kubejs.mini_slime.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.mini_slime.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:mini_vampire')
    .addDefault(Text.translatable('tooltips.kubejs.mini_vampire.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.mini_vampire.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:chicken_heart')
    .addDefault(Text.translatable('tooltips.kubejs.chicken_heart.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:chicken_kidney')
    .addDefault(Text.translatable('tooltips.kubejs.chicken_kidney.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:chicken_lung')
    .addDefault(Text.translatable('tooltips.kubejs.chicken_lung.default.1').gray())
)
