// priority: 900
// 缺失的杂项器官 tooltip

RegistryOrganTooltip(new MultiStateTooltip('kubejs:ore_lung')
    .addDefault(Text.translatable('tooltips.kubejs.ore_lung.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ore_lung.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.ore_lung.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:desire_of_midas')
    .addDefault(Text.translatable('tooltips.kubejs.desire_of_midas.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.desire_of_midas.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.desire_of_midas.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:redstone_furnace')
    .addDefault(Text.translatable('tooltips.kubejs.redstone_furnace.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.redstone_furnace.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.redstone_furnace.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:holy_eyeball')
    .addDefault(Text.translatable('tooltips.kubejs.holy_eyeball.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:excited_appendix')
    .addDefault(Text.translatable('tooltips.kubejs.excited_appendix.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.excited_appendix.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.excited_appendix.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.excited_appendix.alt.3'))
    .addAlt(Text.translatable('tooltips.kubejs.excited_appendix.alt.4'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:stomach_tumor')
    .addDefault(Text.translatable('tooltips.kubejs.stomach_tumor.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:origin_of_tumor')
    .addDefault(Text.translatable('tooltips.kubejs.origin_of_tumor.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.origin_of_tumor.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.origin_of_tumor.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:creeper_appendix')
    .addDefault(Text.translatable('tooltips.kubejs.creeper_appendix.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.creeper_appendix.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.creeper_appendix.alt.2'))
)
