// priority: 900
// 远古器官 tooltip
RegistryOrganTooltip(new MultiStateTooltip('kubejs:prehistory_lung')
    .addDefault(Text.translatable('tooltips.kubejs.prehistory_lung.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:prehistory_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.prehistory_muscle.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:prehistory_heart')
    .addDefault(Text.translatable('tooltips.kubejs.prehistory_heart.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:prehistory_intestine')
    .addDefault(Text.translatable('tooltips.kubejs.prehistory_intestine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:prehistory_rib')
    .addDefault(Text.translatable('tooltips.kubejs.prehistory_rib.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:prehistory_spine')
    .addDefault(Text.translatable('tooltips.kubejs.prehistory_spine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:prehistory_spleen')
    .addDefault(Text.translatable('tooltips.kubejs.prehistory_spleen.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:prehistory_stomach')
    .addDefault(Text.translatable('tooltips.kubejs.prehistory_stomach.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:prehistory_kidney')
    .addDefault(Text.translatable('tooltips.kubejs.prehistory_kidney.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:prehistory_liver')
    .addDefault(Text.translatable('tooltips.kubejs.prehistory_liver.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:prehistory_appendix')
    .addDefault(Text.translatable('tooltips.kubejs.prehistory_appendix.default.1').gray())
)
