// priority: 900
RegistryOrganTooltip(new MultiStateTooltip('kubejs:greed_shard')
    .addAlt(Text.translatable('tooltips.kubejs.greed_shard.alt.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:nether_star_shard')
    .addDefault(Text.translatable('tooltips.kubejs.nether_star_shard.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.nether_star_shard.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:sloth_shard')
    .addDefault(Text.translatable('tooltips.kubejs.sloth_shard.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.sloth_shard.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:wrath_shard')
    .addDefault(Text.translatable('tooltips.kubejs.wrath_shard.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.wrath_shard.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:envy_shard')
    .addDefault(Text.translatable('tooltips.kubejs.envy_shard.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.envy_shard.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:gluttony_shard')
    .addDefault(Text.translatable('tooltips.kubejs.gluttony_shard.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.gluttony_shard.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lust_shard')
    .addDefault(Text.translatable('tooltips.kubejs.lust_shard.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.lust_shard.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:pride_shard')
    .addDefault(Text.translatable('tooltips.kubejs.pride_shard.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.pride_shard.alt.1'))
)
