// priority: 900
RegistryOrganTooltip(new MultiStateTooltip('kubejs:greed_shard')
    .addAlt(Text.translatable('tooltips.kubejs.greed_shard.alt.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:nether_star_shard')
    .addCtrl(Text.translatable('tooltips.kubejs.nether_star_shard.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:sloth_shard')
    .addCtrl(Text.translatable('tooltips.kubejs.sloth_shard.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:wrath_shard')
    .addCtrl(Text.translatable('tooltips.kubejs.wrath_shard.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.wrath_shard.ctrl.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:envy_shard')
    .addCtrl(Text.translatable('tooltips.kubejs.envy_shard.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:gluttony_shard')
    .addCtrl(Text.translatable('tooltips.kubejs.gluttony_shard.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:lust_shard')
    .addCtrl(Text.translatable('tooltips.kubejs.lust_shard.ctrl.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:pride_shard')
    .addCtrl(Text.translatable('tooltips.kubejs.pride_shard.ctrl.1'))
)