// priority: 900
// 温度器官 tooltip

// 烈焰
RegistryOrganTooltip(new MultiStateTooltip('kubejs:flame_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.flame_muscle.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.flame_muscle.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:flame_heart')
    .addDefault(Text.translatable('tooltips.kubejs.flame_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.flame_heart.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.flame_heart.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:flame_stomach')
    .addDefault(Text.translatable('tooltips.kubejs.flame_stomach.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.flame_stomach.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:flame_spine')
    .addDefault(Text.translatable('tooltips.kubejs.flame_spine.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.flame_spine.alt.1'))
)

// 冰霜
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_heart')
    .addDefault(Text.translatable('tooltips.kubejs.ice_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ice_heart.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.ice_heart.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_rib')
    .addDefault(Text.translatable('tooltips.kubejs.ice_rib.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ice_rib.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.ice_rib.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_lung')
    .addDefault(Text.translatable('tooltips.kubejs.ice_lung.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ice_lung.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_intestine')
    .addDefault(Text.translatable('tooltips.kubejs.ice_intestine.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ice_intestine.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ice_piece')
    .addDefault(Text.translatable('tooltips.kubejs.ice_piece.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ice_piece.alt.1'))
)

// 温度
RegistryOrganTooltip(new MultiStateTooltip('kubejs:chameleon_stomach')
    .addDefault(Text.translatable('tooltips.kubejs.chameleon_stomach.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.chameleon_stomach.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.chameleon_stomach.alt.2'))
)

// 九头蛇
RegistryOrganTooltip(new MultiStateTooltip('kubejs:hydra_fiery_blood_essence')
    .addDefault(Text.translatable('tooltips.kubejs.hydra_fiery_blood_essence.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.hydra_fiery_blood_essence.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.hydra_fiery_blood_essence.alt.2'))
)
