// priority: 900
// 暮色森林器官 tooltip

RegistryOrganTooltip(new MultiStateTooltip('kubejs:snow_monster_core')
    .addDefault(Text.translatable('tooltips.kubejs.snow_monster_core.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.snow_monster_core.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:etched_paper')
    .addDefault(Text.translatable('tooltips.kubejs.etched_paper.default.1').gray())
    .addCtrl(Text.translatable('tooltips.kubejs.etched_paper.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.etched_paper.ctrl.2'))
    .addCtrl(Text.translatable('tooltips.kubejs.etched_paper.ctrl.3'))
    .addCtrl(Text.translatable('tooltips.kubejs.etched_paper.ctrl.4'))
    .addCtrl(Text.translatable('tooltips.kubejs.etched_paper.ctrl.5'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:cloud_pyramid')
    .addDefault(Text.translatable('tooltips.kubejs.cloud_pyramid.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.cloud_pyramid.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.cloud_pyramid.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.cloud_pyramid.alt.3'))
    .addAlt(Text.translatable('tooltips.kubejs.cloud_pyramid.alt.4'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:minotaur_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.minotaur_muscle.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.minotaur_muscle.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.minotaur_muscle.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:questing_ram_answer')
    .addDefault(Text.translatable('tooltips.kubejs.questing_ram_answer.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.questing_ram_answer.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.questing_ram_answer.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:knightphantom_ghost')
    .addDefault(Text.translatable('tooltips.kubejs.knightphantom_ghost.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.knightphantom_ghost.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:energetic_naga_scale')
    .addDefault(Text.translatable('tooltips.kubejs.energetic_naga_scale.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.energetic_naga_scale.alt.1'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:twilight_broken_lich_crown')
    .addDefault(Text.translatable('tooltips.kubejs.twilight_broken_lich_crown.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.twilight_broken_lich_crown.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.twilight_broken_lich_crown.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.twilight_broken_lich_crown.alt.3'))
    .addAlt(Text.translatable('tooltips.kubejs.twilight_broken_lich_crown.alt.4'))
    .addAlt(Text.translatable('tooltips.kubejs.twilight_broken_lich_crown.alt.5'))
    .addAlt(Text.translatable('tooltips.kubejs.twilight_broken_lich_crown.alt.6'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:armor_with_gaze')
    .addDefault(Text.translatable('tooltips.kubejs.armor_with_gaze.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.armor_with_gaze.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.armor_with_gaze.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:minoshroom_totem')
    .addDefault(Text.translatable('tooltips.kubejs.minoshroom_totem.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.minoshroom_totem.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.minoshroom_totem.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.minoshroom_totem.alt.3'))
    .addAlt(Text.translatable('tooltips.kubejs.minoshroom_totem.alt.4'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:carminite_reactor_core')
    .addDefault(Text.translatable('tooltips.kubejs.carminite_reactor_core.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.carminite_reactor_core.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.carminite_reactor_core.alt.2'))
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:snow_queen_eternal_sorrow')
    .addDefault(Text.translatable('tooltips.kubejs.snow_queen_eternal_sorrow.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.snow_queen_eternal_sorrow.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.snow_queen_eternal_sorrow.alt.2'))
)