// priority: 500
// 幻想种器官 — 纯分数，无行为策略

RegistryOrgan('kubejs:fantasy_lung')
    .addScore('chestcavity:breath_recovery', 1.125)
    .addScore('chestcavity:breath_capacity', 1.125)
    .addScore('chestcavity:endurance', 1.125)
    .addScore('chestcavity:crystalsynthesis', 0.25)
    .addScore('chestcavity:burning_point', 6)
    .addScore('chestcavity:freezing_point', -3)
    .setCanSpawn(true)

RegistryOrgan('kubejs:fantasy_muscle')
    .addScore('chestcavity:strength', 1.125)
    .addScore('chestcavity:speed', 1.125)
    .addScore('chestcavity:crystalsynthesis', 0.25)
    .addScore('chestcavity:burning_point', 1)
    .addScore('chestcavity:freezing_point', -6)
    .setCanSpawn(true)

RegistryOrgan('kubejs:fantasy_heart')
    .addScore('chestcavity:health', 1.125)
    .addScore('chestcavity:crystalsynthesis', 0.25)
    .addScore('chestcavity:burning_point', 6)
    .addScore('chestcavity:freezing_point', -6)
    .setCanSpawn(true)

RegistryOrgan('kubejs:fantasy_intestine')
    .addScore('chestcavity:nutrition', 1.125)
    .addScore('chestcavity:crystalsynthesis', 0.25)
    .addScore('chestcavity:burning_point', -2)
    .addScore('chestcavity:freezing_point', 4)
    .setCanSpawn(true)

RegistryOrgan('kubejs:fantasy_rib')
    .addScore('chestcavity:defense', 1.125)
    .addScore('chestcavity:crystalsynthesis', 0.25)
    .addScore('chestcavity:burning_point', 4)
    .addScore('chestcavity:freezing_point', -4)
    .setCanSpawn(true)

RegistryOrgan('kubejs:fantasy_spine')
    .addScore('chestcavity:defense', 0.5625)
    .addScore('chestcavity:nerves', 1.125)
    .addScore('chestcavity:crystalsynthesis', 0.25)
    .addScore('chestcavity:burning_point', -3)
    .addScore('chestcavity:freezing_point', 3)
    .setCanSpawn(true)

RegistryOrgan('kubejs:fantasy_spleen')
    .addScore('chestcavity:metabolism', 1.125)
    .addScore('chestcavity:crystalsynthesis', 0.25)
    .addScore('chestcavity:burning_point', -6)
    .addScore('chestcavity:freezing_point', 3)
    .setCanSpawn(true)

RegistryOrgan('kubejs:fantasy_stomach')
    .addScore('chestcavity:digestion', 1.125)
    .addScore('chestcavity:crystalsynthesis', 0.25)
    .addScore('chestcavity:burning_point', -6)
    .addScore('chestcavity:freezing_point', 6)
    .setCanSpawn(true)

RegistryOrgan('kubejs:fantasy_kidney')
    .addScore('chestcavity:filtration', 1.125)
    .addScore('chestcavity:crystalsynthesis', 0.25)
    .addScore('chestcavity:burning_point', -4)
    .addScore('chestcavity:freezing_point', 6)
    .setCanSpawn(true)

RegistryOrgan('kubejs:fantasy_liver')
    .addScore('chestcavity:detoxification', 1.125)
    .addScore('chestcavity:crystalsynthesis', 0.25)
    .addScore('chestcavity:burning_point', -1)
    .addScore('chestcavity:freezing_point', 3)
    .setCanSpawn(true)

RegistryOrgan('kubejs:fantasy_appendix')
    .addScore('chestcavity:luck', 1.125)
    .addScore('chestcavity:crystalsynthesis', 0.25)
    .addScore('chestcavity:burning_point', 2)
    .addScore('chestcavity:freezing_point', -1)
    .setCanSpawn(true)
